### ISSUE TITLE
xmap_df implementation

### ISSUE THREAD

**Issue by cynthiahqy** [cynthiahqy/conformr#57]
_Originally posted by @cynthiahqy in https://github.com/cynthiahqy/conformr-project/issues/43#issuecomment-1378234317_:
> There are a few types of checks that need to happen when forming a valid `xmap`:
> 1. R specific data.frame/S3 attribute checks
> 2. general data.frame format/size/column types
> 3. logical conditions on the graph encoded by the `xmap`

The logical condition checks in 3. could in theory be applied to an `xmap` stored in a different data format (e.g. a JSON graph or a Matrix object). The checks would be implemented slightly differently, and you would still need to convert back to a data frame to apply to transformation using relational joins.

Using this conceptual distinction between data structure properties and "abstract" graph properties, I add use the parent class `xmap` objects for anything that satisfy the graph properties, with sub-classes (i.e. `xmap_df`) for the data structure checks. The most likely additional sub-class that might be needed is a matrix structure (i.e. for perturbation of weights).

## `xmap_df` Construction and Validation

> Tick off each item once it has been implemented

`new_xmap_df(x, from, to weights)` requires that:
- [x] `x` is a data.frame-like object
- [x] `from`, `to`, `weights` arguments are all `character values of length 1`
- [x] `from_set` is a `character vector`
- It assumed, but not checked that:
	- (`x` contains the column named in `from`, `to`, `weights` arguments?)
	- (the `from_set` vector attributes contains all unique values of `from` column in `x`)
	- (the `weights` column contains numeric weights)
	- (the first three columns are in order `from`, `to`, `weights`)

If `new_x` is the `xmap_df` object returned by `new_xmap_df(x, from, to, weights)`. Then `new_x`:
- [x] has `col_from`, `col_to`, `col_weights` attributes which are character values of length 1
- [x] has `from_set` attribute which is a `character vector`.
- [x] has class attributes `xmap_df` and `xmap`

Then `validate_xmap_df(new_x)` ensures that:
- `new_x` is a data.frame-like object and:
	- [x] contains the columns named in the `col_from`, `col_to`, `col_weights` attributes
	- [x] is column sorted as: `<col_from>`, `<col_to>`, `<col_weights>` #62 
	- [x] has no missing values
	- [x] the character vector of all unique values in the `col_from` variable exactly match the `from_set` attribute
	- [x] the `col_weights` column is a numeric vector
- [x] `new_x` inherits from the class `xmap_df`
- [ ] `new_x` inherits from the class `xmap`

`validate_xmap_df(new_x)` also checks that `new_x` has:
- [x] has only one weighted link between each source-target pair of form:
	- `{source: "A1", target: "B01", weight: 1}`
- [x] for every source node, the weights on all (outgoing) links sum to 1 
	- [x] subject to some floating point tolerance? #30 

## `xmap_df` coercion

`as_xmap_df(x, from, to, weights, other)` should:
- [x] always return a `xmap_df` object
- [x] retains additional columns not drop them (too strict)
- [ ] accepts tidyselect specification for `from`, `to`, `weights`
- [ ] sorts columns in order of `from`, `to`, `weights`, <other cols> #62 
- [ ] retain factor / character class of `from` and `to` columns as given by user (in `x`)

Offer/Test the following unclassing functions
- [ ] `as_tibble(xmap_df)`
- [ ] `as_data.frame(xmap_df)`

## `xmap_df` read/write #62 

- use column position to encode `from`, `to`, `weights`, `other` column metadata

- READ `xmap_from_csv(path, col_from = NULL, col_to = NULL, col_weights = NULL)`

`xmap_to_csv(path)` should:
- [ ] WRITE column sorted `xmap_df` to `.csv`

**Comment by cynthiahqy** [comment]
### Allow `xmap_df` to have more than 3 columns

- allows user to keeps extra information (code descriptions), weight calculation method etc. in the `xmap_df`
- allows multiple weight scheme to be stored in the same `xmap_df` --> "activate" different weight schemes.

interface options for `as_map()`:

- dropping argument: `as_map(x, from, to, weights, .drop = FALSE)`
- other cols argument: `as_map(x, from, to, weights, other = NULL)` -- keep everything else by default, but allow for tidy-select of specific columns to keep

TO-DO
- [x] remove ncol3 checks from `validate_xmap_df`
- [x] add column dropping argument to `as_xmap_df`
- [x] edit reference doc in https://github.com/cynthiahqy/conformr-paper/issues/9#issuecomment-1397865759

**Comment by cynthiahqy** [comment]
### Implement `xmap_validate()` as a generic with method for `xmap_df`

- [x] for `xmap_df`: `validate_xmap.xmap_df()` via alias `xmap_validate.xmap_df` <- `validate_xmap_df`

**Comment by cynthiahqy** [comment]
Basic implementation finished with #71. Other features are planned for later implementation.
