### ISSUE TITLE
Quality of Life Enhancements to xmap

### ISSUE THREAD

**Issue by cynthiahqy** [cynthiahqy/conformr#64]
A thread for quality of life improvements. These will most likely not be implemented in the first release of {xmap}. This to allow me to switch back to developing {conformr} workflows using the existing `xmap_df` implementation. Many features lend themselves to introducing some kind of dependence on tidyverse which needs some consideration.

- [ ] #87
- [ ] #63 
- [ ] pretty error messages #59 
- [ ] floating point tolerance using `dplyr::near()` #30
- [ ] wrapper for importing `xmap` from csv #62
- [ ] switch `as_xmap_df()` to `weights = NULL` and have a default "weights" = 1 internally (needs tidy select) #78
